library(rjson)
# options("download.file.method" = "libcurl")
# devtools::install_github("shihikoo/pubmedTools")
library(pubmedTools)
library(XML)
library(tidyr)
library(data.table)

pmids <- c("28852052", "29041955","31230181")
print(RetriveMetaDataFromPmidsBatch(pmids))
